/**
 * Career Talks — data contract.
 *
 * This is the SINGLE source of truth for the shape of a career talk
 * everywhere in the app:
 *   - the spreadsheet parser produces `CareerTalk[]`
 *   - the localStorage layer stores `CareerTalk[]`
 *   - the future real backend API will return `CareerTalk[]`
 *   - the listing + details pages render `CareerTalk[]`
 *
 * Keep this file PERMANENTLY. When the senior wires the real API,
 * they just need to make the API return objects that match this
 * interface (or transform inside `useCareerTalks.ts` once). Pages
 * never change.
 */

export interface CareerTalk {
  /** Unique identifier used in the URL route `/career-talks/[id]`.
   *  Auto-generated by the sheet parser from the row index ("1",
   *  "2", …). When the API ships, the backend's own id (string or
   *  number cast to string) goes here. */
  id: string;

  /** Headline title — shown on the card and as the details-page H1. */
  title: string;

  /** One-paragraph hook shown as the lead paragraph on the details
   *  page (just under the meta row). Maps to the "Short Description"
   *  column in the upload sheet. */
  shortDescription: string;

  /** Full body text shown in the details-page description card. May
   *  contain multiple paragraphs separated by `\n\n`. Maps to the
   *  "Long Description" column in the sheet. */
  longDescription: string;

  /** Employer / sponsor name. Drives the Employers filter chip on the
   *  listing page when present. Maps to the "Company" column. */
  company: string;

  /** Display-ready date string ("Tuesday, March 3, 2026") — produced
   *  by the parser from the sheet's "Date of Podcast" cell. Keeping
   *  the formatted string in the data means the pages don't need a
   *  date library at render time. */
  date: string;

  /** ISO date (YYYY-MM-DD) used purely for SORTING the cards by
   *  date. Never displayed. The parser fills both `date` and
   *  `dateISO` from the same source cell. */
  dateISO: string;

  /** Time-range label rendered next to the clock icon on the details
   *  page meta row. Free-form string ("5pm - 7pm"). Maps to the
   *  "Timings" column. */
  time: string;

  /** Skill / topic tags shown as small chips on the details page —
   *  decorative only, not a filter. The parser splits the sheet's
   *  comma-separated "Keywords" cell into this array. */
  keywords: string[];

  /** URL of the card thumbnail + the details-page banner image.
   *  Maps to the "Image URL" column. Empty string is treated as
   *  "no image" by the renderer (falls back to gradient placeholder). */
  imageUrl: string;

  /** Source URL for the Event Video on the details page. May be a
   *  direct MP4 link OR a YouTube URL — `videoSourceType.ts` detects
   *  which and the details page renders the matching player. Maps
   *  to the "Youtube URL" column. */
  videoUrl: string;
}
